// ============================================================
// GARRINCHA · data, fixtures (clearly placeholder) + i18n
// ============================================================

// ---- Flags: national flags drawn in CSS (circular). Not tournament marks. ----
const FLAGS = {
  BEL: 'linear-gradient(90deg,#2B2B2B 0 33.3%,#FFD90F 33.3% 66.6%,#F31830 66.6%)',
  FRA: 'linear-gradient(90deg,#0055A4 0 33.3%,#fff 33.3% 66.6%,#EF4135 66.6%)',
  NED: 'linear-gradient(180deg,#AE1C28 0 33.3%,#fff 33.3% 66.6%,#21468B 66.6%)',
  ITA: 'linear-gradient(90deg,#008C45 0 33.3%,#fff 33.3% 66.6%,#CD212A 66.6%)',
  GER: 'linear-gradient(180deg,#111 0 33.3%,#DD0000 33.3% 66.6%,#FFCE00 66.6%)',
  ESP: 'linear-gradient(180deg,#AA151B 0 25%,#F1BF00 25% 75%,#AA151B 75%)',
  POR: 'linear-gradient(90deg,#046A38 0 40%,#DA291C 40%)',
  ARG: 'linear-gradient(180deg,#74ACDF 0 33.3%,#fff 33.3% 66.6%,#74ACDF 66.6%)',
  BRA: 'linear-gradient(135deg,#009C3B 0 40%,#FFDF00 40% 60%,#009C3B 60%)',
  ENG: 'conic-gradient(#fff 0 100%)', // cross drawn separately
  CRO: 'linear-gradient(180deg,#FF0000 0 33%,#fff 33% 66%,#171796 66%)',
  MAR: 'linear-gradient(135deg,#C1272D 0 100%)',
  TBD: 'repeating-linear-gradient(45deg,#2a332a 0 8px,#222a22 8px 16px)',
};
const FLAG_LABEL = {
  BEL:'Belgium', FRA:'France', NED:'Netherlands', ITA:'Italy', GER:'Germany',
  ESP:'Spain', POR:'Portugal', ARG:'Argentina', BRA:'Brazil', ENG:'England',
  CRO:'Croatia', MAR:'Morocco', TBD:'To be decided',
};

// ---- GARRINCHA Centers (placeholder) ----
const CENTERS = [
  { id:'antwerp',   name:'Antwerp',    short:'ANT', city:'Antwerp',   color:'#5FE090', players:0 },
  { id:'brussels',  name:'Brussels',   short:'BRU', city:'Brussels',  color:'#F5C242', players:0 },
  { id:'ghent',     name:'Ghent',      short:'GNT', city:'Ghent',     color:'#6FB3FF', players:0 },
  { id:'liege',     name:'Liège',      short:'LIE', city:'Liège',     color:'#FF8C66', players:0 },
  { id:'leuven',    name:'Leuven',     short:'LEU', city:'Leuven',    color:'#C792EA', players:0 },
  { id:'bruges',    name:'Bruges',     short:'BRG', city:'Bruges',    color:'#4ED9C0', players:0 },
];

// ---- Match fixtures — PLACEHOLDER campaign data ----
// status: open | live | locked | finished
const MATCHES = [
  { id:'m1', stage:'Group A · MD1', home:'BEL', away:'FRA', date:'Tue 09 Jun', time:'18:00', status:'open',  pred:null },
  { id:'m2', stage:'Group A · MD1', home:'NED', away:'ITA', date:'Tue 09 Jun', time:'21:00', status:'open',  pred:null },
  { id:'m3', stage:'Group B · MD1', home:'GER', away:'ESP', date:'Wed 10 Jun', time:'18:00', status:'live',  live:'67\'', sc:[1,1], pred:null },
  { id:'m4', stage:'Group B · MD1', home:'POR', away:'ARG', date:'Wed 10 Jun', time:'21:00', status:'open',  pred:null },
  { id:'m5', stage:'Group C · MD1', home:'BRA', away:'ENG', date:'Thu 11 Jun', time:'18:00', status:'locked',time:'18:00', pred:[2,1] },
  { id:'m6', stage:'Group C · MD1', home:'CRO', away:'MAR', date:'Thu 11 Jun', time:'21:00', status:'open',  pred:null },
  { id:'m7', stage:'Group A · MD1', home:'TBD', away:'TBD', date:'Fri 12 Jun', time:'18:00', status:'open',  pred:null },
];

// finished examples for "results / points earned" demo (clearly placeholder)
const RESULTS = [
  { id:'r1', stage:'Group D · MD1', home:'ITA', away:'BEL', date:'Sun 07 Jun', final:[2,1], pred:[2,1], pts:5 },
  { id:'r2', stage:'Group D · MD1', home:'ESP', away:'NED', date:'Sun 07 Jun', final:[1,1], pred:[2,2], pts:2 },
  { id:'r3', stage:'Group E · MD1', home:'FRA', away:'GER', date:'Sat 06 Jun', final:[3,0], pred:[2,1], pts:0 },
];

const SCORING = [
  { pts:5, key:'sc_exact' },
  { pts:3, key:'sc_diff' },
  { pts:2, key:'sc_out' },
  { pts:0, key:'sc_wrong' },
];

// ============================================================
// i18n  ·  EN / NL / FR
// ============================================================
const I18N = {
  en:{
    lang_name:'English',
    // nav
    nav_home:'Home', nav_predict:'Predict', nav_ranks:'Ranks', nav_prizes:'Prizes', nav_you:'You',
    // landing
    tagline:'Scan · Predict · Represent',
    hero_title:'PREDICT THE\nWORLD CUP.\nREPRESENT YOUR\nCENTER.',
    hero_sub:'Free to play. Scan the QR code at any GARRINCHA Center, call the scores, and climb your center to the top of the table.',
    cta_register:'Register for free',
    cta_have_link:'I have an access link',
    how_title:'How it works',
    how_1_t:'Scan at a center', how_1_d:'Find the QR code at any GARRINCHA Center and scan it with your phone.',
    how_2_t:'Register for free', how_2_d:'Name, email, nickname. Receive your personal access link by email.',
    how_3_t:'Continue remotely', how_3_d:'Your link never expires — return anytime, from any device, anywhere.',
    how_4_t:'Represent a center', how_4_d:'Choose the center you compete for. It locks after your first prediction.',
    how_5_t:'Predict & climb', how_5_d:'Call every score. Predictions lock 5 minutes after kickoff.',
    prize_teaser:'Top players per center win the prize challenge',
    scoring_title:'How points work',
    sc_exact:'Exact score', sc_diff:'Right result + goal difference', sc_out:'Right result only', sc_wrong:'Wrong prediction',
    points:'points', point:'point', pts:'pts',
    // qr / register
    qr_active:'QR activated', qr_center:'Center detected',
    reg_title:'Create your free account', reg_sub:'Takes under a minute.',
    f_name:'Full name', f_email:'Email address', f_phone:'Contact number', f_nick:'Nickname',
    f_nick_hint:'This is the name shown on leaderboards.',
    consent:'I agree to the Terms and Privacy Policy.',
    create_account:'Create my account',
    no_qr_title:'Scan a center QR first',
    no_qr_body:'Registration opens after you scan the QR code at a GARRINCHA Center. No code? Visit any center to join.',
    sent_title:'Check your email',
    sent_body:'We sent your personal access link to',
    sent_note:'Your link never expires. Open it anytime to continue from any device.',
    sent_open:'Open my dashboard',
    err_required:'Required', err_email:'Enter a valid email', err_consent:'Please accept to continue',
    // dashboard
    welcome:'Welcome', remote_access:'Remote access',
    remote_note:'You can continue from any device. Your access link never expires.',
    first_activation:'First activation',
    choose_center:'Choose your competition center',
    choose_center_sub:'Pick the center you want to represent. It locks after your first prediction.',
    center_locked:'Representing', center_locked_note:'Locked after your first prediction',
    your_points:'Your points', global_rank:'Global rank', center_rank:'Center rank',
    matchday:'Matchday', open_preds:'open predictions',
    upcoming:'Upcoming matches', view_all:'View all',
    lock_note:'Predictions lock 5 minutes after kickoff',
    // predict
    predict_title:'Predict', your_pred:'Your prediction', save_pred:'Save prediction', saved:'Saved',
    open:'Open', live:'Live', locked:'Locked', finished:'Finished', ft:'FT',
    earned:'earned', kickoff:'Kickoff',
    empty_pred_t:'No predictions yet', empty_pred_d:'Your saved predictions will appear here.',
    // leaderboard
    ranks_title:'Leaderboards', tab_global:'Global', tab_center:'My center',
    player:'Player', center:'Center',
    empty_board_t:'No leaderboard results yet', empty_board_d:'Rankings appear once matches are scored.',
    you_label:'You',
    // prizes
    prizes_title:'Prize winners', prizes_sub:'Top players per center win the challenge.',
    filter_center:'Filter by center', all_centers:'All centers',
    empty_prize_t:'No prize winners yet', empty_prize_d:'Winners are announced when the campaign ends.',
    // states
    choose_first:'Choose a center before predicting',
    // admin
    admin:'Admin', super_admin:'Super Admin', center_admin:'Center Admin', system_health:'System Health',
  },
  nl:{
    lang_name:'Nederlands',
    nav_home:'Start', nav_predict:'Voorspel', nav_ranks:'Stand', nav_prizes:'Prijzen', nav_you:'Jij',
    tagline:'Scan · Voorspel · Vertegenwoordig',
    hero_title:'VOORSPEL HET\nWK.\nVERTEGENWOORDIG\nJOUW CENTER.',
    hero_sub:'Gratis spelen. Scan de QR-code in een GARRINCHA Center, voorspel de scores en stuw jouw center naar de top.',
    cta_register:'Gratis registreren',
    cta_have_link:'Ik heb een toegangslink',
    how_title:'Hoe het werkt',
    how_1_t:'Scan in een center', how_1_d:'Vind de QR-code in een GARRINCHA Center en scan met je telefoon.',
    how_2_t:'Gratis registreren', how_2_d:'Naam, e-mail, bijnaam. Ontvang je persoonlijke toegangslink per e-mail.',
    how_3_t:'Ga later verder', how_3_d:'Je link verloopt nooit — kom terug wanneer je wil, op elk toestel.',
    how_4_t:'Vertegenwoordig', how_4_d:'Kies het center waarvoor je speelt. Het vergrendelt na je eerste voorspelling.',
    how_5_t:'Voorspel & klim', how_5_d:'Voorspel elke score. Voorspellingen sluiten 5 min na aftrap.',
    prize_teaser:'Topspelers per center winnen de prijzenstrijd',
    scoring_title:'Hoe punten werken',
    sc_exact:'Exacte score', sc_diff:'Juiste uitslag + doelsaldo', sc_out:'Enkel juiste uitslag', sc_wrong:'Foute voorspelling',
    points:'punten', point:'punt', pts:'ptn',
    qr_active:'QR geactiveerd', qr_center:'Center herkend',
    reg_title:'Maak je gratis account', reg_sub:'Duurt minder dan een minuut.',
    f_name:'Volledige naam', f_email:'E-mailadres', f_phone:'Telefoonnummer', f_nick:'Bijnaam',
    f_nick_hint:'Deze naam verschijnt op de ranglijsten.',
    consent:'Ik ga akkoord met de Voorwaarden en Privacy.',
    create_account:'Account aanmaken',
    no_qr_title:'Scan eerst een center-QR',
    no_qr_body:'Registratie opent nadat je de QR-code in een GARRINCHA Center scant. Geen code? Bezoek een center.',
    sent_title:'Check je e-mail',
    sent_body:'We stuurden je persoonlijke toegangslink naar',
    sent_note:'Je link verloopt nooit. Open hem wanneer je wil, op elk toestel.',
    sent_open:'Open mijn dashboard',
    err_required:'Verplicht', err_email:'Geldig e-mailadres', err_consent:'Aanvaard om verder te gaan',
    welcome:'Welkom', remote_access:'Externe toegang',
    remote_note:'Ga verder op elk toestel. Je toegangslink verloopt nooit.',
    first_activation:'Eerste activatie',
    choose_center:'Kies je competitiecenter',
    choose_center_sub:'Kies het center dat je vertegenwoordigt. Vergrendelt na je eerste voorspelling.',
    center_locked:'Vertegenwoordigt', center_locked_note:'Vergrendeld na je eerste voorspelling',
    your_points:'Jouw punten', global_rank:'Globale stand', center_rank:'Center-stand',
    matchday:'Speeldag', open_preds:'open voorspellingen',
    upcoming:'Komende matchen', view_all:'Alles',
    lock_note:'Voorspellingen sluiten 5 min na aftrap',
    predict_title:'Voorspel', your_pred:'Jouw voorspelling', save_pred:'Bewaar voorspelling', saved:'Bewaard',
    open:'Open', live:'Live', locked:'Gesloten', finished:'Afgelopen', ft:'ET',
    earned:'verdiend', kickoff:'Aftrap',
    empty_pred_t:'Nog geen voorspellingen', empty_pred_d:'Je bewaarde voorspellingen verschijnen hier.',
    ranks_title:'Ranglijsten', tab_global:'Globaal', tab_center:'Mijn center',
    player:'Speler', center:'Center',
    empty_board_t:'Nog geen resultaten', empty_board_d:'Ranglijsten verschijnen zodra matchen gescoord zijn.',
    you_label:'Jij',
    prizes_title:'Prijswinnaars', prizes_sub:'Topspelers per center winnen de strijd.',
    filter_center:'Filter op center', all_centers:'Alle centers',
    empty_prize_t:'Nog geen winnaars', empty_prize_d:'Winnaars worden bekendgemaakt na de campagne.',
    choose_first:'Kies een center voor je voorspelt',
    admin:'Beheer', super_admin:'Super Admin', center_admin:'Center Admin', system_health:'Systeemstatus',
  },
  fr:{
    lang_name:'Français',
    nav_home:'Accueil', nav_predict:'Pronostic', nav_ranks:'Classement', nav_prizes:'Prix', nav_you:'Profil',
    tagline:'Scanner · Pronostiquer · Représenter',
    hero_title:'PRONOSTIQUEZ\nLA COUPE.\nREPRÉSENTEZ\nVOTRE CENTRE.',
    hero_sub:'Gratuit. Scannez le QR code dans un GARRINCHA Center, pronostiquez les scores et hissez votre centre en tête.',
    cta_register:'Inscription gratuite',
    cta_have_link:'J’ai un lien d’accès',
    how_title:'Comment ça marche',
    how_1_t:'Scannez au centre', how_1_d:'Trouvez le QR code dans un GARRINCHA Center et scannez-le.',
    how_2_t:'Inscription gratuite', how_2_d:'Nom, e-mail, pseudo. Recevez votre lien d’accès personnel par e-mail.',
    how_3_t:'Continuez à distance', how_3_d:'Votre lien n’expire jamais — revenez quand vous voulez, sur tout appareil.',
    how_4_t:'Représentez un centre', how_4_d:'Choisissez votre centre. Il se verrouille après votre premier pronostic.',
    how_5_t:'Pronostiquez & grimpez', how_5_d:'Pronostiquez chaque score. Verrouillage 5 min après le coup d’envoi.',
    prize_teaser:'Les meilleurs par centre gagnent le challenge',
    scoring_title:'Le barème de points',
    sc_exact:'Score exact', sc_diff:'Bon résultat + différence de buts', sc_out:'Bon résultat seul', sc_wrong:'Mauvais pronostic',
    points:'points', point:'point', pts:'pts',
    qr_active:'QR activé', qr_center:'Centre détecté',
    reg_title:'Créez votre compte gratuit', reg_sub:'Moins d’une minute.',
    f_name:'Nom complet', f_email:'Adresse e-mail', f_phone:'Numéro de contact', f_nick:'Pseudo',
    f_nick_hint:'Ce nom apparaît dans les classements.',
    consent:'J’accepte les Conditions et la Confidentialité.',
    create_account:'Créer mon compte',
    no_qr_title:'Scannez d’abord un QR',
    no_qr_body:'L’inscription s’ouvre après avoir scanné le QR code d’un GARRINCHA Center. Pas de code ? Visitez un centre.',
    sent_title:'Vérifiez vos e-mails',
    sent_body:'Nous avons envoyé votre lien d’accès à',
    sent_note:'Votre lien n’expire jamais. Ouvrez-le sur tout appareil.',
    sent_open:'Ouvrir mon tableau de bord',
    err_required:'Requis', err_email:'E-mail invalide', err_consent:'Veuillez accepter pour continuer',
    welcome:'Bienvenue', remote_access:'Accès à distance',
    remote_note:'Continuez sur tout appareil. Votre lien n’expire jamais.',
    first_activation:'Première activation',
    choose_center:'Choisissez votre centre',
    choose_center_sub:'Choisissez le centre que vous représentez. Verrouillé après le 1er pronostic.',
    center_locked:'Représente', center_locked_note:'Verrouillé après votre premier pronostic',
    your_points:'Vos points', global_rank:'Classement global', center_rank:'Classement centre',
    matchday:'Journée', open_preds:'pronostics ouverts',
    upcoming:'Matchs à venir', view_all:'Tout voir',
    lock_note:'Verrouillage 5 min après le coup d’envoi',
    predict_title:'Pronostic', your_pred:'Votre pronostic', save_pred:'Enregistrer', saved:'Enregistré',
    open:'Ouvert', live:'Direct', locked:'Verrouillé', finished:'Terminé', ft:'TT',
    earned:'gagnés', kickoff:'Coup d’envoi',
    empty_pred_t:'Aucun pronostic', empty_pred_d:'Vos pronostics enregistrés apparaîtront ici.',
    ranks_title:'Classements', tab_global:'Global', tab_center:'Mon centre',
    player:'Joueur', center:'Centre',
    empty_board_t:'Aucun résultat', empty_board_d:'Les classements apparaissent une fois les matchs notés.',
    you_label:'Vous',
    prizes_title:'Gagnants', prizes_sub:'Les meilleurs par centre gagnent le challenge.',
    filter_center:'Filtrer par centre', all_centers:'Tous les centres',
    empty_prize_t:'Aucun gagnant', empty_prize_d:'Les gagnants sont annoncés à la fin de la campagne.',
    choose_first:'Choisissez un centre avant de pronostiquer',
    admin:'Admin', super_admin:'Super Admin', center_admin:'Admin Centre', system_health:'État système',
  },
};

Object.assign(window, { FLAGS, FLAG_LABEL, CENTERS, MATCHES, RESULTS, SCORING, I18N });
